-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Libro"
(
    "ISBN" integer NOT NULL DEFAULT nextval('"Libro_ISBN_seq"'::regclass),
    autor character varying COLLATE pg_catalog."default" NOT NULL,
    titulo character varying COLLATE pg_catalog."default" NOT NULL,
    id_tema integer,
    CONSTRAINT "Libro_pkey" PRIMARY KEY ("ISBN")
);

CREATE TABLE IF NOT EXISTS public."Prestamo"
(
    id_prestamo integer NOT NULL DEFAULT nextval('"Prestamo_id_prestamo_seq"'::regclass),
    fecha_prestamo date NOT NULL,
    fecha_devolucion date NOT NULL,
    "ISBN" integer NOT NULL,
    id_socio integer NOT NULL,
    CONSTRAINT "Prestamo_pkey" PRIMARY KEY (id_prestamo)
);

CREATE TABLE IF NOT EXISTS public."Socio"
(
    id_socio integer NOT NULL DEFAULT nextval('"Socio_id_socio_seq"'::regclass),
    nombre character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Socio_pkey" PRIMARY KEY (id_socio)
);

CREATE TABLE IF NOT EXISTS public."Tema"
(
    id_tema integer NOT NULL DEFAULT nextval('"Tema_id_tema_seq"'::regclass),
    tema character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Tema_pkey" PRIMARY KEY (id_tema)
);

ALTER TABLE IF EXISTS public."Libro"
    ADD CONSTRAINT id_tema FOREIGN KEY (id_tema)
    REFERENCES public."Tema" (id_tema) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Prestamo"
    ADD CONSTRAINT "ISBN" FOREIGN KEY ("ISBN")
    REFERENCES public."Libro" ("ISBN") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Prestamo"
    ADD CONSTRAINT id_socio FOREIGN KEY (id_socio)
    REFERENCES public."Socio" (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;